spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.app.entity
  mapperLocations: classpath:mapper/*.xml
  global-config:
    #自定义SQL注入器 
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector 
  