server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3002/ctc_customer
    username: customer_app_user
    password: mney4v9djer#U
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource