server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3002/ctc_customer
    username: customer_app_user
    password: mney4v9djer#U
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: cwl19910230
    timeout: 10    #秒
    jedis:
      pool:
        max-wait: 10
        max-active: 8
        max-idle: 8
        min-idle: 2
        test-while-idle: true
        test-on-borrow: true
        
  application: 
    name: spirng-boot-rabbitmq
  rabbitmq: 
    host: 127.0.0.1
    port: 5672
    username: admin
    password: cwl19910230
    virtual-host: /ctc
    publisher-confirms: true
    publisher-returns: true
    listener: 
      acknowledge-mode: MANUAL

